# Generated by Django 2.1.5 on 2022-04-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
